---
title: "Other Media"
---

This seems like a good a place as any to highlight other places I've appeared in the past, like, five years.

### Podcast Appearances

I've never had my own podcast - and have no plans to - but have appeared on those of friends' a few times. If you'd like me to appear on your podcast, get in touch, but also, why?

-   [Post-Podium: A Jeopardy Retrospective](https://open.spotify.com/show/3h5ciKBuER63EyTYtmB44I)

    -   [Second Chance Competition Analysis](https://open.spotify.com/episode/6fkDvpLIL5qUsHulyx39FV) (August 14, 2022)

    -   [2022 Jeopardy! Tournament of Champions Preview](https://open.spotify.com/episode/11wM9dy2F7hqJLo6GcRWVf) (September 9, 2022)

-   [Advent Calendar House](https://adventcalendar.house/)

    -   [A Rugrats Passover](https://adventcalendar.house/episodes/rugrats-passover) (July 7, 2023)

-   [The Benchwarmers Trivia Podcast](https://benchwarmerstriviapodcast.com/)

    -   [Ep 241: Summer Sanders.... NOW!](https://open.spotify.com/episode/64EYi6MYtImPc1qZ1o1N8T) (February 20, 2024)

### Game Show Marathon

Since 2023, I've participated in [Game Show Marathon](https://gameshowmarathon.com/), a 24-hour live Twitch stream and telethon of people recreating classic and current game shows to raise money for [Child's Play](https://gameshowmarathon.com/about-childs-play/). You can check out their [YouTube channel](https://www.youtube.com/@24HourGSM/videos) for clips from previous marathons; I won't exhaustively list which videos I appear in simply because I don't want to, but to start you can check out me participating in [The Floor (GSM 2024)](https://www.youtube.com/watch?v=ucX95LKwoko) and [Mastermind (GSM 2023)](https://www.youtube.com/watch?v=Lf6_dkhvyaI&t=1s).
