---
title: "A List of Every Major Sporting Event I've Attended"
---

## Full List

**Last updated February 1, 2025.**

### Baseball 

#### MLB

9-14-2007: Phillies 3 \@ Mets 2 (10) <br /> 6-23-2009: Cardinals 3 \@ Mets 0 <br /> 6-25-2010: Twins 2 \@ Mets 5 <br /> 8-10-2010: Rockies 0 \@ Mets 1 <br /> 9-3-2010: Nationals 5 \@ Pirates 8 <br /> 9-6-2010: Braves 1 \@ Pirates 3 <br /> 4-8-2011: Rockies 3 \@ Pirates 4 (14) <br /> 7-7-2011: Rays 5 \@ Yankees 1 <br /> 9-10-2011: Marlins 3 \@ Pirates 0 <br /> 4-20-2012: Cardinals 4 \@ Pirates 1 <br /> <br /> 7-23-2012: Nationals 8 \@ Mets 2 (10) <br /> 7-25-2012: Nationals 5 \@ Mets 2 <br /> 5-3-2013: Nationals 1 \@ Pirates 3 <br /> 7-12-2013: Mets 2 \@ Pirates 3 (11) <br /> 6-29-2014: Mets 2 \@ Pirates 5 <br /> 8-15-2014: Padres 2 \@ Cardinals 4 <br /> 9-25-2016: Phillies 0 \@ Mets 17 <br /> 6-7-2017: Mets 4 \@ Rangers 3 <br /> 6-4-2018: Yankees 7 \@ Tigers 4 <br /> 6-5-2018: Brewers 2 \@ Indians 3 <br /> <br /> 6-7-2018: Dodgers 8 \@ Pirates 7 <br /> 8-9-2018: Braves 3 \@ Nationals 6 <br /> 9-22-2018: Mets 0 \@ Nationals 6 <br /> 5-6-2019: Red Sox 1 \@ Orioles 4 <br /> 5-14-2019: Mets 6 \@ Nationals 2 <br /> 8-25-2019: Rays 3 \@ Orioles 8 <br /> 9-2-2019: Mets 7 \@ Nationals 3 <br /> 6-19-2021: Mets 5 \@ Nationals 1 (7) <br /> 7-28-2021: Marlins 7 \@ Orioles 8 <br /> 9-3-2021: Mets 6 \@ Nationals 2 (10) <br /> <br /> 4-9-2022: Mets 5 \@ Nationals 0 <br /> 6-11-2022: Brewers 6 \@ Nationals 8 <br /> 6-29-2022: Pirates 8 \@ Nationals 7 <br /> 6-22-2023: Diamondbacks 5 \@ Nationals 3 <br /> 7-23-2023: Giants 1 \@ Nationals 6 <br /> 6-3-2024: Mets 8 \@ Nationals 7 <br /> 6-20-2024: Diamondbacks 5 \@ Nationals 2 <br /> 7-12-2024: Rockies 6 \@ Mets 7 <br /> 7-19-2024: Reds 5 \@ Nationals 8 <br /> 9-13-2024: Athletics 2 \@ White Sox 0 <br /> <br />

#### Minor Leagues

<br /> 9-7-2015: Memphis 7 \@ Oklahoma City 3 (AAA) <br /> 5-15-2016: Las Vegas 9 \@ Oklahoma City 7 (AAA) <br /> 8-8-2017: Florida 2 \@ St. Lucie 4 (High A) <br /> 4-5-2018: Charlotte 6 \@ Durham 2 (AAA) <br /> <br />

### Basketball

#### NBA

<br /> 4-19-2006: Knicks 90 \@ Nets 83 <br /> 12-23-2009: Timberwolves 103 \@ Nets 99 <br /> 1-2-2014: Nets 95 \@ Thunder 93 <br /> 12-11-2014: Cavaliers 94 \@ Thunder 103 <br /> 3-8-2015: Raptors 104 \@ Thunder 108 <br /> 4-7-2015: Spurs 113 \@ Thunder 88 <br /> 11-22-2015: Mavericks 114 \@ Thunder 117 <br /> 12-26-2015: Wizards 111 \@ Nets 96 <br /> 3-24-2016: Jazz 91 \@ Thunder 113 <br /> 10-30-2016: Lakers 96 \@ Thunder 113 <br /> <br /> 11-9-2016: Raptors 112 \@ Thunder 102 <br /> 2-26-2017: Pelicans 110 \@ Thunder 118 <br /> 12-20-2017: Jazz 79 \@ Thunder 107 <br /> 12-29-2017: Bucks 97 \@ Thunder 95 <br /> 1-6-2018: Nuggets 98 \@ Kings 106 <br /> 2-26-2018: Magic 105 \@ Thunder 112 <br /> 10-30-2019: Rockets 159 \@ Wizards 158 <br /> 1-3-2020: Trail Blazers 122 \@ Wizards 103 <br /> 10-30-2021: Celtics 112 \@ Wizards 115 (2OT) <br /> 11-13-2022: Grizzlies 92 \@ Wizards 102 <br /> <br /> 3-22-2023: Nuggets 118 \@ Wizards 104 <br /> 11-10-2023: Hornets 124 \@ Wizards 117 <br /> 1-8-2024: Thunder 136 \@ Wizards 128 <br /> 10-26-2024: Cavaliers 135 \@ Wizards 116 <br /> <br />

#### NCAA

<br /> 2-15-2009: Clemson 81 \@ Virginia 85 (OT) <br /> 11-13-2010: North Florida 49 \@ Pittsburgh 85 <br /> 12-18-2010: Maryland-ES 64 \@ Pittsburgh 97 <br /> 1-8-2011: Marquette 81 \@ Pittsburgh 89 <br /> 1-15-2011: Seton Hall 53 \@ Pittsburgh 74 <br /> 1-17-2011: Syracuse 66 \@ Pittsburgh 74 <br /> 2-5-2011: Cincinnati 59 \@ Pittsburgh 71 <br /> 11-11-2011: Albany 56 \@ Pittsburgh 89 <br /> 12-6-2011: VMI 70 \@ Pittsburgh 97 <br /> 12-17-2011: South Carolina St 55 \@ Pittsburgh 69 <br /> <br /> 1-21-2012: Louisville 73 \@ Pittsburgh 62 <br /> 1-28-2012: Georgetown 60 \@ Pittsburgh 72 <br /> 2-19-2012: South Florida 56 \@ Pittsburgh 47 <br /> 11-9-2012: Mt. St. Mary's 48 \@ Pittsburgh 80 <br /> 11-17-2012: Oakland 62 \@ Pittsburgh 72 (OT) <br /> 12-5-2012: Duquesne 45 vs. Pittsburgh 66 <br /> 1-5-2013: Pittsburgh 62 \@ Rutgers 67 <br /> 1-26-2013: DePaul 55 \@ Pittsburgh 93 <br /> 2-2-2013: Syracuse 55 \@ Pittsburgh 65 <br /> 3-14-2013: Cincinnati 43 vs. Georgetown 62 <br /> <br /> 3-14-2013: Syracuse 62 vs. Pittsburgh 59 <br /> 11-20-2013: Lehigh 58 \@ Pittsburgh 77 <br /> 12-6-2013: Loyola Marymount 68 \@ Pittsburgh 85 <br /> 1-22-2014: Clemson 43 \@ Pittsburgh 76 <br /> 12-19-2015: Creighton 74 \@ Oklahoma 87 <br /> 12-30-2015: Indiana 79 \@ Rutgers 72 <br /> 2-20-2016: Texas Tech 71 \@ Oklahoma St 61 <br /> 3-10-2016: North Carolina 88 vs. Pittsburgh 71 <br /> 3-10-2016: Duke 79 vs. Notre Dame 84 (OT) <br /> 3-18-2016: VCU 75 vs. Oregon St 67 <br /> <br /> 3-18-2016: Cal St Bakersfield 68 vs. Oklahoma 82 <br /> 3-18-2016: Northern Iowa 75 vs. Texas 72 <br /> 3-20-2016: VCU 81 vs. Oklahoma 85 <br /> 3-20-2016: Northern Iowa 88 vs. Texas A&M 92 (2OT) <br /> 2-18-2017: Northern Iowa 44 \@ Wichita St 73 <br /> 3-8-2017: Wake Forest 90 vs. Virginia Tech 99 <br /> 3-8-2017: Pittsburgh 63 vs. Virginia 75 <br /> 1-3-2018: Oklahoma State 89 \@ Oklahoma 109 <br /> 12-8-2018: Valparaiso 82 \@ George Washington 79 <br /> 1-15-2019: Marquette 74 \@ Georgetown 71 <br /> <br /> 2-2-2019: Syracuse 65 \@ Pittsburgh 56 <br /> 2-9-2019: Butler 73 \@ Georgetown 69 <br /> 3-2-2019: Seton Hall 71 \@ Georgetown 77 (2OT) <br /> 11-8-2019: William & Mary 79 \@ American 70 <br /> 2-17-2024: Richmond 90 \@ George Washington 74 <br /> 3-14-2024: Florida St 67 vs. North Carolina 92 <br /> 3-14-2024: Wake Forest 69 vs. Pittsburgh 81 <br /> 3-15-2024: Pittsburgh 65 vs. North Carolina 72 <br /> 3-15-2024: NC State 73 vs. Virginia 65 (OT) <br /> <br />

### Hockey

#### NHL

<br /> 2-7-2006: Lightning 4 \@ Devils 7 <br /> 10-3-2013: Devils 0 \@ Penguins 3 <br /> 10-26-2021: Flames 5 \@ Devils 3 <br /> <br />

### Football

#### NFL

I have actually never attended an NFL game! Crazy!

#### College

<br /> 10-18-2008: Richmond 30 \@ UMass 15 (FCS) <br /> 9-11-2010: New Hampshire 16 \@ Pitt 38 <br /> 10-2-2010: FIU 17 \@ Pitt 44 <br /> 10-23-2010: Rutgers 21 \@ Pitt 41 <br /> 9-3-2011: Buffalo 16 \@ Pitt 35 <br /> 9-24-2011: Notre Dame 15 \@ Pitt 12 <br /> 10-15-2011: Utah 26 \@ Pitt 14 <br /> 9-15-2012: Virginia Tech 17 \@ Pitt 35 <br /> 9-2-2013: Florida St 41 \@ Pitt 13 <br /> 11-9-2013: Notre Dame 21 \@ Pitt 28 <br /> <br /> 11-15-2014: Pitt State 41 \@ Central Oklahoma 14 (D2) <br /> 9-17-2016: Pitt 38 \@ Oklahoma State 45 <br /> 9-2-2017: Youngstown State 21 \@ Pitt 28 (OT) <br /> 9-1-2022: West Virginia 31 \@ Pitt 38 <br /> 10-19-2024: USC 28 \@ Maryland 29 <br /> <br />

### Soccer

<br /> 6-18-2010: New York Red Bulls 2 - 4 Cruzeiro <br /> 10-11-2015: OKC Energy FC 1 - 2 Los Angeles Galaxy II <br /> 3-12-2017: New York City FC 4 - 0 DC United <br /> 10-13-2018: DC United 1 - 0 FC Dallas <br /> 9-15-2021: DC United 3 - 0 Chicago Fire <br /> 6-25-2022: DC United 1 - 3 Nashville SC <br /> 6-17-2023: DC United 1 - 2 Real Salt Lake <br />
